# This is a basic workflow to help you get started with Actions

name: Continouis Integration Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feature/branch ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name:  RUN AZ command
        run: |
          az account show
          az group list

      - name: login with azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.azure_credentials }}'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: always()
        run: echo Hello, world!
        
      - name: running a custom step
        run: |
            ls -al

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: check java version
        run: java -version

      - name: gradle build
        run: gradle build

      - name: gradlew build
        run: ./gradlew build
        
      - name: docker version
        run: |
          docker -v
          docker
          docker images -a

      - name: docker build
        run: |
          docker build . -t cyraa/demo-kotlin2.0
          docker images -a

      - name: docker login
        run: docker login -u ${{ secrets.dockerhubusername }} -p ${{ secrets.dockerhubpassword }}

      - name: docker image push
        run: docker push cyraa/demo-kotlin2.0

      
